[package]
name = "sark_grids"
version = "0.1.0"
edition = "2021"
authors = ["sark"]
homepage = "https://github.com/sarkahn/sark_grids_rs"
repository = "https://github.com/sarkahn/sark_grids_rs"
license = "MIT"
readme = "README.md"
keywords = ["2d", "grid", "sparse_grid"]

[dependencies]
glam = { version = "0.20.0" }
itertools = "0.10.3"